version: '3.7'

services:
  app:
    container_name: country_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3009:3009'
    environment:
      - PORT=3009
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=""
      - DB_NAME=country_api
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    depends_on:
      - database
      - redis
    networks:
      - country_api_network

  redis:
    container_name: country_api_redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    networks:
      - country_api_network

  database:
    container_name: country_api_mysql
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: country_api
    networks:
      - country_api_network

volumes:
  redis:
    driver: local
  mysql-data:
    driver: local

networks:
  country_api_network:
