version: '3.7'

services:
  redis:
    container_name: country_api_redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data

  mysql:
      container_name: country_api_mysql
      image: mysql:8.0
      ports:
        - 3306:3306
      volumes:
        - mysql-data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: country_api
        MYSQL_USER: root
        MYSQL_PASSWORD: 

  app:
    container_name: country_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: ['npm', 'run', 'start:dev']

volumes:
  redis:
    driver: local
  mysql-data:
    driver: local
