on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/global-country-insights
            sudo docker compose down
            git stash
            # Set git config
            git config --global credential.helper none
            git pull origin main
            sudo docker compose up --build -d
            until sudo docker-compose logs app | grep -q "port: 6379"; do
              sleep 5
            done

            echo "Container is ready. Running migrations..."
            sudo docker exec country_api npm run migration:run
            echo "Done"
