on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/global-country-insights
            sudo docker compose down
            git stash
            # Set git config
            git config --global credential.helper none
            git pull origin main
            sudo docker compose up --build -d
            # Wait for the container to be fully up
            echo "Waiting for container to be ready..."
            sleep 30

            # Check if the container is running
            if sudo docker ps | grep -q "country_api"; then
              echo "Container is running. Running migrations..."
              sudo docker exec country_api npm run migration:run
            else
              echo "Error: Container is not running."
              exit 1
            fi

            echo "Deployment completed successfully."
            echo "Done"
